### PR TITLE
made view for brandon guest

### PR DESCRIPTION
**Pull request by bcmyguest**

### CODE REVIEW

**Review by srowhani — APPROVED** [review]

**Comment by Skilleen** [comment]
LGTM

**Comment by Jasonjys** [comment]
wow this is amazing. So smart.

**Comment by awaisabir** [comment]
This is awesome! 2406 and Git 👏

**Review by awaisabir — APPROVED** [review]

**Comment by jQwotos** [comment]
@awaisabir yo what you doing here XD

**Pull request closed without merging**
