### PR TITLE
Make the move to JavaScript ES6 & Improve Readability

### PR DESCRIPTION
**Pull request by matthew-e-brown**
ES6 `const` and `let` are so much more elegant than `var`, don't you agree?

I also took the liberty of using template literals to replace some clunky string concatenations.

### CODE REVIEW

**Comment by matthew-e-brown** [comment]
... I hope this doesn't come across as rude and/or condescending 😅❤

**Comment by jQwotos** [comment]
LGTM

**Comment by jQwotos** [comment]
Awesome job @matthew-e-brown . Thanks for your help!

**Comment by matthew-e-brown** [comment]
Thanks @jQwotos. I try my best 😉
Your class's code actually helped me quite a bit when it came time to update my personal website -- I had no idea about `module.exports`. Helped me make it more organized during my effort to move to `EJS`. 😃

**Pull request merged**
